### ISSUE TITLE
Unwinding kernels need fixing

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/gkylzero#11]
Seems there is an error in the upwind kernels. The copysignf function only applies to float and not doubles. Hence, its use is not appropriate in the kernel as we are working with doubles and not floats. Just use the copysign function; it is “type-generic” and will pick the proper float/double based on the input values.

However, a more serious question is: why is this logic needed? I believe this code can be significantly simplified and perhaps even made faster by only computing the left/right value based on the sign of alpha at the node. Writing the flux as:

Flux = (fr+fl)/2 + abs(alpha)*(fr-fl)/2

is wasteful. We can write it instead as:

Flux = fr  (if alpha > 0) or Flux = fl (if alpha < 0)

This means only fr or fl need to computed and not both. This could save FLOPS and hence improve performance. 

Further, I think the interpolation code can be simplified by storing basis-functions at quad-nodes (as we do in proj_on_basis) and then writing a dot-product function that is called to compute fl/fr as needed (depending on the sign of alpha).

Perhaps this is best explained on a call, but just writing all this before I forget it.

**Comment by manauref** [comment]
Yes this seems reasonable.

And it is true that there's no need to evaluate basis functions at nodes
over and over again. You weren't doing that in g1 if I'm not mistaken.

**Comment by JunoRavin** [comment]
What we are doing in upwinding currently is unrolling a matrix-vector product that evaluates the distribution function at quadrature points. This operation seems to have zero performance difference for small basis sets (maybe up to about 32 basis functions), but balloons for the higher dimensions and polynomial order and is likely not optimal anyway (I expect the compiler at some point does not like an unrolled expression that's 10k operations).

Interpolation code would significantly clean up this operation and reduce the size of the kernels, making it feasible to actually go to higher polynomial orders in higher dimensions than we currently do. Further, the interpolation code *could* be a heavily optimized matrix-vector product, because it's a dense operation anyway. We should vectorize and optimize the interpolation as much as feasible.

**Comment by ammarhakim** [comment]
We don't want to do a mat-vec product, actually. Instead we want to do a dot product. So the sequence would be:

1. For each quad-point determine the direction of alpha
2. Then depending on the direction, compute f_face = fL or fR ... this is a vector-vector dot product (values of basis at quad dot expansion coefficients)
3. Reconstruct surface expansion and do rest of algorithm

This means at each quad node we only compute EITHER fL or fR but not both. This will cut the flops by 2x for computing upwinded numerical flux.

**Comment by ammarhakim** [comment]
The latest work in the upwind branch that was merged to main fixes this and other issues. Closing it.
