### ISSUE TITLE
G0 App broken on GPUs due to non-device memory used for periodic BCs sync

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkylzero#161]
The null_comm which is created for serial simulations through the G0 app handles periodic boundary conditions now (as periodic boundary conditions are handled by the communicator object) but the buffers that are being created by the null_comm are not on the device, so GPU simulations run through the G0 app seg fault. Need to detect if the communicator is "on device" so that the buffers are created in the right place.

**Comment by ammarhakim** [comment]
One outstanding issue is what to do with all_reduce? At present, the all_reduce is still on CPU. Which seems the proper thing for the current Vlasov App. However, the semantics could be confusing as one may assume all_reduce is also on GPU. Perhaps one should add a `all_cu_reduce` method to the communicators.

This is fixed in PR #167. Once that PR is merged this can be closed.
