### ISSUE TITLE
CUDA memory management (ref counting)

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/gkylzero#2]
We need to come-up with a proper way to manage memory allocations and deallocations of CUDA objects on device. Typically these objects have life-times that of the simulation and so probably it does not matter, but an analogous reference counting mechanism should be implemented as is on the host-side. This will allow acquiring pointers safely to device objects and doing deep copies properly.

Overall, some of the deep copying needs to be looked into again carefully.

**Comment by nmandell** [comment]
One possibility is similar to what we were doing in G2: we could keep pointers to the device struct (and host-side pointers to device data in the device struct) inside the corresponding host struct (in G2 this was the onDevice members). For array, this would mean extra gkyl_array elements void * device_data and gkyl_array * device_struct, where device_data is the host-side pointer to the device data in the device struct (the pointer cannot be accessed directly on host from device_struct->data because device_struct is on device). When we want to free the host struct we will also have all the pointers necessary to free the device data and struct.

**Comment by ammarhakim** [comment]
This issue is resolved in the gpu_vm_lbo_2 branch; essentially, the idea is what Noah articulated and that was implemented in the array. Further, the branch also has code to trace memory allocations, allowing a proper check of mem-leaks both on GPU and CPU code.

(For some reason valgrind won't work with nvcc build even for host code. Also, cuda-memcheck will not report errors even there are leaks. I am not sure how to use it. In any case, though valgrind is very powerful and useful, my mem-tracing code adds 0 overhead, while valgrind is extremely slow. So we can even use mem-tracing even in production runs. Of course, mem-tracing can't give full stack information like valgrind can but at least one can get info that mem has leaked and what part of the code leaked it).
