### ISSUE TITLE
Stop g0-app-driven sims when the time step gets too small

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#249]
This prevents us from wasting computer time and filling up our drives with junk (e.g. I have a sim in which the sim log file was 640 MB because of NaN messages in it, and the sim tried to keep running for many more hours before I caught it and killed it).

One possibility, like we did in g2, is to check if the time step has dropped a factor of 1e-4 below its initial time step (for consecutive time steps), in which case we terminate the sim.

**Comment by JunoRavin** [comment]
This is currently controlled at the C input file level, not within the app itself, because the app doesn't know what the end time or initial timestep of a simulation is. It only knows how to take a timestep. That's why the loop over steps/until the end time happens in your C input file.

You can flexible set the minimum dt one wants within the input ctx like I do in a number of input files here: https://github.com/ammarhakim/gkylzero/blob/main/regression/rt_pkpm_alf_wave_1x_p1.c

**Comment by ammarhakim** [comment]
There is nothing to do here. As Jimmy said above the individual main driver can choose to monitor the time-step and quit when it becomes too small. The way G0 Apps are structured is that they do not have the main loop. All the looping is done in the drivers and they are free to stop if they wish to.
