### ISSUE TITLE
A flag turning off the evolution of collisionless term

### ISSUE THREAD

**Issue by dingyunl** [ammarhakim/gkylzero#260]
It would significantly speed up the regression test with a flag turning off the evolution of collisionless term. I have been testing the GkBGK collisions operator. There is a still a problem with the cross collisions on gpu, so I can only run it on cpu currently, and it takes very long time to run the full regression tests. 

Could you please help me implementing such a flag? @JunoRavin

**Comment by ammarhakim** [comment]
I am not sure which regression test you are running. Regression tests should run quickly. Also, flags are easy to implement and I can show you how to do this. But first, which test is this and why does it take so long?

**Comment by manauref** [comment]
@ammarhakim I suggested to @dingyunl and @JunoRavin that we run some BGK-only tests (without collisionless terms, sheaths or sources), preferably in curvilinear geometry (to test correct handling of jacobians), but starting with slab is good too. These tests should be checked for convergence towards the correct steady state of the BGK equation. Otherwise, running ASDEX or LAPD simulations just to test BGK is going to take too long and may not correctly identify errors in the BGK implementation.

**Comment by ammarhakim** [comment]
I am not against this. But I think we need to be careful and thoughtful on making requests on features. I can point out how to do this, as I said above.
