### ISSUE TITLE
MPI RPATH breaks GPU build (on Stellar and Perlmutter)

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#375]
Line 69 in the Makefile
```
       MPI_RPATH = -Wl,-rpath,${CONF_MPI_LIB_DIR}
```

Breaks the build on stellar-amd and Perlmutter GPU.

For now we have just been manually deleting this line to make things work.

**Comment by ammarhakim** [comment]
I recommend someone who has an issue sit with me to fix. This is needed for G2 to work properly and so we must have rpath. But maybe there is some small path error.Sent from my iPhoneOn May 28, 2024, at 6:51 PM, Manaure Francisquez ***@***.***> wrote:﻿
Line 69 in the Makefile
       MPI_RPATH = -Wl,-rpath,${CONF_MPI_LIB_DIR}

Breaks the build on stellar-amd and Perlmutter GPU.
For now we have just been manually deleting this line to make things work.

**Comment by manauref** [comment]
I forgot to add the error message, here it is:

```
make: *** [Makefile:329: cuda-build/libgkylzero.so] Error 1
make: *** Waiting for unfinished jobs....
nvcc fatal   : Unknown option '-Wl,-rpath,/opt/cray/pe/mpich/8.1.28/ofi/gnu/12.3/lib'
make: *** [Makefile:339: cuda-build/libgkylzero-install.so] Error 1
```

**Comment by ammarhakim** [comment]
This seems like a problem with nvcc linker. We should bring this up the Nvidia mentor. The rpath is not the problem here, clearly. It’s possible for nvcc we need another flag.Sent from my iPhoneOn May 29, 2024, at 10:31 PM, Manaure Francisquez ***@***.***> wrote:﻿
I forgot to add the error message, here it is:
make: *** [Makefile:329: cuda-build/libgkylzero.so] Error 1
make: *** Waiting for unfinished jobs....
nvcc fatal   : Unknown option '-Wl,-rpath,/opt/cray/pe/mpich/8.1.28/ofi/gnu/12.3/lib'
make: *** [Makefile:339: cuda-build/libgkylzero-install.so] Error 1

**Comment by manauref** [comment]
For the record, for now we are currently fixing this locally by deleting L69 from the Makefile:
```
       MPI_RPATH = -Wl,-rpath,${CONF_MPI_LIB_DIR}
```

**Comment by fglines-nv** [comment]
You can pass linker options directly to the linker with `-Xlinker`. See the documentation here: https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#linker-options-options-xlinker

I think `--forward-unknown-to-host-linker` would accomplish the same thing in this specific case.

Alternatively, you could forgo this option and use the environment variable `LD_LIBRARY_PATH` to point to the library, although I prefer `rpath` over `LD_LIBRARY_PATH`.

**Comment by fglines-nv** [comment]
To be more clear, we added `-Xlinker "-rpath,/opt/cray/pe/mpich/8.1.28/ofi/gnu/12.3/lib"`

**Comment by manauref** [comment]
This is addressed here
https://github.com/ammarhakim/gkylzero/commit/9142728a3e55ea9d208889c6072fa30eb221ed41

**Comment by ammarhakim** [comment]
I think this issue is now fixed.
