### ISSUE TITLE
[DR] Emission boundary conditions in gk-g0-app

### ISSUE THREAD

**Issue by kltrbrds** [ammarhakim/gkylzero#397]
A full implementation (CPU and GPU) of emission boundary conditions into the gk-g0-app branch (as opposed to the previous partial implementation designed to work solely through g2-g0) is in https://github.com/ammarhakim/gkylzero/tree/gk-g0-emission-spectrum.

The majority of the new proposed infrastructure is self-contained within three methods, `vm_species_emission`, `bc_emission_spectrum`, and `bc_emission_elastic`. The first is the g0 app plugin for the emission, the second is the inelastic emission spectrum calculation, and the final is the elastic backscattering calculation. The emission model being implemented matches what is described in Section 4.3 of https://vtechworks.lib.vt.edu/handle/10919/118137, with the modification that the weighted average of the secondary electron yield is done over the boundary flux instead of the skin cell distribution.

The major global change done to the Vlasov-Maxwell app is the modification of the BCs to match what is done in gyrokinetics. Boundary conditions are now passed in the form:
```
.bcx = {
  .lower = { .type = GKYL_SPECIES_ABSORB, },
  .upper = { .type = GKYL_SPECIES_EMISSION,
             .aux_ctx = &bc_ctx, },
},
```
This allows for specification of the auxiliary structures required for various emission models.

Because the impacting species causing emission and the species being emitted are not necessarily the same (such as with ion-impact secondary electron emission), an additional cross-species initialization method is called for the new `vm_species_emission` after all species have initialized. Further, `gkyl_vlasov_app_apply_ic` is modified to compute the boundary condition after IC's are applied to all species, due to the same constraint.

High-emission simulations show it is sometimes desirable to scale the emission with time, to  prevent too severe of an initial emitted density gradient from developing in the skin cell. This requires a minor modification to the `forward_euler` method in the app, passing `tcurr` as an additional argument to `vm_species_apply_bc`.

The regression test `rt_vlasov_emission_spectrum_1x1v_p2` was added to demonstrate functionality. Currently, the user is required to create BC and model-specific structures and pass them through a `void*` pointer to the BC, like so:
```
  struct gkyl_bc_emission_spectrum_norm_chung_everhart *chung_ctx = gkyl_malloc(sizeof(struct gkyl_bc_emission_spectrum_norm_chung_everhart));
  struct gkyl_bc_emission_spectrum_yield_furman_pivi *furman_ctx = gkyl_malloc(sizeof(struct gkyl_bc_emission_spectrum_yield_furman_pivi));
  struct gkyl_bc_emission_elastic_furman_pivi *furman_elastic_ctx = gkyl_malloc(sizeof(struct gkyl_bc_emission_elastic_furman_pivi));
  
  chung_ctx->mass = 9.109e-31;
  chung_ctx->charge = -1.602e-19;
  chung_ctx->phi = 4.68;

  furman_ctx->mass = 9.109e-31;
  furman_ctx->charge = -1.602e-19;
  furman_ctx->deltahat_ts = 1.885;
  furman_ctx->Ehat_ts = 276.8;
  furman_ctx->t1 = 0.66;
  furman_ctx->t2 = 0.8;
  furman_ctx->t3 = 0.7;
  furman_ctx->t4 = 1.0;
  furman_ctx->s = 1.54;

  furman_elastic_ctx->mass = 9.109e-31;
  furman_elastic_ctx->charge = -1.602e-19;
  furman_elastic_ctx->P1_inf = 0.02;
  furman_elastic_ctx->P1_hat = 0.496;
  furman_elastic_ctx->E_hat = 1.0e-6;
  furman_elastic_ctx->W = 60.86;
  furman_elastic_ctx->p = 1.0;

 struct vm_emission_ctx bc_ctx = {
    .num_species = 1,
    .elastic = true,
    .norm_type = { GKYL_SEE_CHUNG_EVERHART },
    .yield_type = { GKYL_SEE_FURMAN_PIVI },
    .elastic_type = GKYL_BS_FURMAN_PIVI,
    .norm_params = { chung_ctx },
    .yield_params = { furman_ctx },
    .elastic_params = furman_elastic_ctx,
    .in_species = { "elc" },
  };
```
These structures are freed internally by the app. A more user-friendly way to do this may be preferable.

**Comment by JunoRavin** [comment]
I am happy with this design and the overall input file structure, at least on the C input file side. It's true we could make this more compact (and it likely will get more compact with the Lua wrapping). @kltrbrds can you file the PR for the official code review?

**Comment by manauref** [comment]
I'd like to learn more about `bc_emission_spectrum` and `bc_emission_elastic`, but we can do that in the CR or in a call this week. A couple of things that come to mind:
1. "`gkyl_vlasov_app_apply_ic` is modified to compute the boundary condition after IC's are applied to all species". We should evaluate how exactly this is being done.
2. The way you are dynamically allocating a structure in the input file and freeing it under the hood is not right and should be changed. Why dynamically allocate? Why can't these be static input structs like we use elsewhere in the code?

**Comment by JunoRavin** [comment]
Adding a comment here to summarize the discussion from the DR meeting last week: 

We determined that a way to do the design more generally is to create three general types that emission BCs expect, with names such as `bc_emission_spectrum_norm_type` `bc_emission_spectrum_yield_type` and `bc_emission_elastic_type`

so that in input files right now that create these structs
https://github.com/ammarhakim/gkylzero/blob/9ee2da46865a8eef75d3b109f5b61d41625a069e/regression/rt_vlasov_emission_spectrum_1x1v_p2.c#L126
https://github.com/ammarhakim/gkylzero/blob/9ee2da46865a8eef75d3b109f5b61d41625a069e/regression/rt_vlasov_emission_spectrum_1x1v_p2.c#L127
https://github.com/ammarhakim/gkylzero/blob/9ee2da46865a8eef75d3b109f5b61d41625a069e/regression/rt_vlasov_emission_spectrum_1x1v_p2.c#L128

we would instead create an object of the more general type with a new method for the derived type **in exact analogy** with moment input files that contain calls such as: 
https://github.com/ammarhakim/gkylzero/blob/9ee2da46865a8eef75d3b109f5b61d41625a069e/regression/rt_10m_gem.c#L273

The BC object would then acquire pointers to these more general types and utilize the contents of the derived types for the specific emission BC. The memory would then be freed **within the C input file** at the end of the input file like so:
https://github.com/ammarhakim/gkylzero/blob/9ee2da46865a8eef75d3b109f5b61d41625a069e/regression/rt_10m_gem.c#L482

These more general types where specific emission BCs are derived types would then immediately permit the flexible deployment of the emission BCs in other applications, such as neutral wall recycling. 

The derived types could then also explicitly encode some natural choices for the parameters that utilize the fits @kltrbrds found to be most effective in his thesis work, and serve as examples should anyone want to come in and add new fits, similar to the success of the radiation operator and the deployment of a wide variety of fits for the radiation drag based on the ion type and charge state being collided with.

**Comment by JunoRavin** [comment]
Design implemented in https://github.com/ammarhakim/gkylzero/pull/431
