### ISSUE TITLE
GPU capability of rect_apply_bc method

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkylzero#6]
To support more general boundary conditions, our current code structure utilizes function pointers to determine how the ghost cells depend on the skin cells (or some more general function independent of the interior of the domain). 

We need to figure out how we're going to port the rect_apply_bc method onto GPUs. Where should the supported functions go (and their corresponding function pointers)? Right now the supported functions are within the app but that may make the G0-G2 merge more painful since we want to retain as much of the G2 app structure as possible. 

And we will need a rect_apply_bc.cu method that performs the loop over the exterior of the domain in a GPU-compatible way.

**Comment by ammarhakim** [comment]
I think this is pretty easy: all we need to do is decorate the functions that apply BCs with GKYL_CU_DH attributes. Then we pass these pointers to a new cu_dev_new() method. 

I also do not understand what is meant by "retain as much of the G2 app structure as possible". The App code in G2 will substantially change, mostly simplify a lot due to decisions being made in the C layer of the code. We will make minimum changes to the input files as far as possible. Ideally, there should not be any change in input files (besides superficial ones). 

In the specific case of the BCs I do not think we need to do anything except ensure that the function pointers are compiled on the device also. Where the pointers are defined is not important. I believe where they are at present is just fine. (I.e. in the vlasov.c or moment.c files). Eventually, we will have priv files so apps can access each others stuff to do hybrid calculations, but that will not substantially change anything.

**Comment by JunoRavin** [comment]
Completed in a separate branch
