### ISSUE TITLE
LBO collisions is currently broken (not conservative)

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#69]
If one runs LBO collision tests, like rt_lbo_vlasov_relax_1x1v_p2 (formerly rt_lbo_relax_1v), you'll notice that the 2nd comment of the distribution function is no longer conserved.

By:
- checking out old commits, and paying attention to what branch that commit came from
- making sure to run the correct executable/test for that commit

I've determined that the problem originated when mom_calc_bcorr, which is used to compute LBO boundary corrections, was modified so that it worked over configuration space (for computing boundary fluxes?) in 134e0d6233823242658694c400b37e7ba3141c8b (and subsequent commit which makes a minor signature fix: d6b27342eb75c2d77b5adc98c349ffa3aa9be3e3).

This caused the current version in main to not conserve moments. You can checkout intermediate commits and think that it works, but that's because you are probably checking out commits that came from the gk-0 branch, where LBO collisions still work. We'd like to fix this in main before we proceed with further merges.

**Comment by JunoRavin** [comment]
To add to this, it's not that the LBO is not conservative, it's that the LBO is completely broken on the CPU side. @kltrbrds and I have narrowed this issue down to some change in gk-0/another branch negatively interacting with the changes to the moment boundary correction calculator that works generally over some specified edge now.

Serendipitously, the GPU implementation actually still works and the LBO and primitive moment unit tests pass on the CPU and GPU. @kltrbrds and I believe this is some issue in the program flow within the app unique to the CPU which we will continue to hunt down. 

Because branches were open for a long time and past commits are interacting in ways that are difficult to pin down just by checking out old commits, we are going to have to step through the app carefully. Again, fortunately we know the answer on the GPU side is correct so we can actually from main (or a new branch from the latest main) step through the app and see where the CPU answer diverges from the GPU answer.

**Comment by ammarhakim** [comment]
@manauref and @JunoRavin @kltrbrds : is this issue fixed? If so, please close the Issue

**Comment by JunoRavin** [comment]
This issue is fixed as of commit: c7f54cd0c036f2066aefe5fc1183e2c396cce043

mom_calc_bcorr has been reverted to its original form in a follow on commit: 59adfa4d485ca1aae496c99d20a33974b6dc71af

The extensions to mom_calc_bcorr that were originally explored but abandoned are maintained for posterity in branch bound-flux and can be resurrected if we find a utility for these extensions (but it was the extensions that were causing the issue and the extensions are not currently utilized, they have been eliminated).
